### ISSUE TITLE
Add more connectivity check URLs in case geoip.kde.org goes down

### ISSUE THREAD

**Issue by K900** [NixOS/calamares-nixos-extensions#11]
It's down right now and there's at least two people on Matrix unable to continue installing.

**Comment by K900** [comment]
It's back up now, but the issue is still relevant.

**Comment by vlinkz** [comment]
Thinking of adding `internetCheckUrl: [ https://geoip.kde.org/v1/calamares, https://cache.nixos.org/ ]`. But do you know if this would be improper use of cache.nixos.org? I'm thinking that since it's about to install packages from there it would make sense to check it first

**Comment by K900** [comment]
I think that makes sense, and it being hosted on Fastly means it should be pretty resilient.

**Comment by vlinkz** [comment]
Done in [#193041](https://github.com/NixOS/nixpkgs/pull/193041)
