### ISSUE TITLE
don't require special `boot.loader.efi.efiSysMountPoint`

### ISSUE THREAD

**Issue by CobaltCause** [NixOS/calamares-nixos-extensions#17]
Every manual install I've done has used the default of `/boot` as the EFI system partition mount point, but the graphical installer requires it to be set to `/boot/efi`. Would be cool if it didn't do that, for consistency with the module defaults and when one does it the manual way.

**Comment by mweinelt** [comment]
Ideally we can make that `/efi` at some point in nixpkgs, per https://0pointer.net/blog/linux-boot-partitions.html.
