### ISSUE TITLE
Wi-Fi connection requires installer restart

### ISSUE THREAD

**Issue by lambdakilo** [NixOS/calamares-nixos-extensions#23]
Connecting to Wi-Fi in the middle of Installer says that the system is not connected to the internet. The installer should maybe refresh the internet connection status more often than only at the launch of the installer.
![image](https://github.com/NixOS/calamares-nixos-extensions/assets/31825085/61f99026-d234-47e3-ac9c-1267fa4428e5)

**Comment by vlinkz** [comment]
This is fixed in an upcoming release of Calamares (see [#1106](https://github.com/calamares/calamares/issues/1106)). Once released it will make it's way to nixpkgs.
