### ISSUE TITLE
Can`t use any password during install

### ISSUE THREAD

**Issue by AldebaraanMKII** [NixOS/calamares-nixos-extensions#38]
**Describe the bug**
There is restrictions on the initial password during install. It keeps saying that my password isn`t strong enough.

**Expected behavior**
User should be able to use any password when installing the OS, no matter how short or simple.

**Comment by DerRockWolf** [comment]
There is a checkbox labeled `Require strong passwords`, when unchecked it will still display a warning but you can just continue with the installation.

**Comment by ElvishJerricco** [comment]
Yep. There's already a solution in the UI for this. Please re-open if we're missing something.
