### ISSUE TITLE
geoip support

### ISSUE THREAD

**Issue by davidak** [NixOS/calamares-nixos-extensions#5]
I have seen in the locale config. that geoip can be used to get the timezone. That seem like a nice feature.
Should we enable it?

Setting the system language to something other than english might not be the best experience since it totally depend on the desktop and programs if they are translated. It's also good to get errors in english to be able to search them. So english is a good default in the welcome screen.

**Comment by vlinkz** [comment]
Done in 8529e7c775f0eb7200d6f1b0ada2938a757a94b6
