### ISSUE TITLE
Clarify LICENSEs

### ISSUE THREAD

**Issue by davidak** [NixOS/calamares-nixos-extensions#7]
There are multiple files in LICENSES directory (copied from upstream) and some files have SPDX headers, but other files have no license information.

Upstream seem to use the REUSE standard, which i think is the best way to do it.

https://reuse.software/

They have it defined here: https://github.com/calamares/calamares-extensions/blob/calamares/.reuse/dep5

**Comment by vlinkz** [comment]
I added some more licenses to the config files based on those from upstream. For the images I put their licenses in the LICENCES folder and described which licenses went to which files in the README. Is there anything else I should add?

**Comment by davidak** [comment]
Looks good. Thank you!
