### ISSUE TITLE
internetCheckUrl:   http://google.com

### ISSUE THREAD

**Issue by davidak** [NixOS/calamares-nixos-extensions#8]
People use linux for privacy. They might not be happy that we connect to google and tell them their IP.

Upstream changed the example because of this reason: https://github.com/calamares/calamares/commit/6bf82e9c656a73e0464b57fe99acb7eb24010372

We could use https://ping.canbeuseful.com/ (hosted by OVH) or also https://geoip.kde.org/v1/calamares (small response, but has to wait for API to generate response).

microsoft have a similar check and are criticised for collecting IPs: https://www.itechtics.com/ncsi/

Other suggesting for reliable site that returns 200 HTTP code and not much else?

**Comment by vlinkz** [comment]
Done in 8529e7c775f0eb7200d6f1b0ada2938a757a94b6. But we could switch to something better down the line
