### ISSUE TITLE
Code leftovers in a comment in the generated NixOS config

### ISSUE THREAD

**Issue by justinas** [NixOS/calamares-nixos-extensions#9]
https://github.com/NixOS/calamares-nixos-extensions/blob/a71b9cea0106d70ae051812a40902dc03c13f3e4/modules/nixos/main.py#L305

This ends up in `configuration.nix` after using the graphical installer. Not familiar with calamares and not sure where the `catenate()` should actually go, so just reporting the issue.

**Comment by vlinkz** [comment]
Must've slipped through the cracks, thanks for creating an issue!

**Comment by vlinkz** [comment]
Fixed with https://github.com/NixOS/nixpkgs/pull/176475 and 969d97f9d16f8e2eae1be7b65b821016026595d8
